apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-planner-frontend-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    cert-manager.io/acme-challenge-type: "http01"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-path: "/"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-404"
    appgw.ingress.kubernetes.io/health-probe-interval: "30"
    appgw.ingress.kubernetes.io/health-probe-timeout: "30"
    appgw.ingress.kubernetes.io/health-probe-unhealthy-threshold: "3"
spec:
  ingressClassName: azure-application-gateway
  tls:
  - hosts:
    - dev.travelplanner.nebulahub.ai
    secretName: travel-planner-frontend-dev-tls
  rules:
  - host: dev.travelplanner.nebulahub.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: travel-planner-frontend
            port:
              number: 80
